Traceback (most recent call last):
  File "geo.py", line 279, in <module>
    size(geo_usos, courts, roads, 5 * 10000, context, "voro_elena_la1")
  File "geo.py", line 195, in size
    uso, npoints, courts_shape, roads_shape, max_size)
  File "/home/cristian/Tesis/Algorithm/Tessellation/voro.py", line 41, in voronoi_tessellation
    voro_features = hc_voronoi(feature, candidates, npoints, maxsize)
  File "/home/cristian/Tesis/Algorithm/Tessellation/voro.py", line 102, in hc_voronoi
    result_features = voronoi(feature, voro_points)
  File "/home/cristian/Tesis/Algorithm/Tessellation/voro.py", line 136, in voronoi
    points, BoundingBox=box, PlotMap=False)
  File "/home/cristian/Tesis/Algorithm/Tessellation/voronoi/voronoi_poly.py", line 290, in VoronoiPolygons
    voronoi.voronoi(siteList,context)
  File "/home/cristian/Tesis/Algorithm/Tessellation/voronoi/voronoi.py", line 195, in voronoi
    lbnd = edgeList.leftbnd(newsite) 
  File "/home/cristian/Tesis/Algorithm/Tessellation/voronoi/voronoi.py", line 598, in leftbnd
    bucket = int(((pt.x - self.xmin)/self.deltax * self.hashsize))
ZeroDivisionError: float division by zero


**********************************************************************************************************************

Traceback (most recent call last):
  File "geo.py", line 279, in <module>
    size(geo_usos, courts, roads, 5 * 10000, context, "voro_sta_carla")
  File "geo.py", line 195, in size
    uso, npoints, courts_shape, roads_shape, max_size)
  File "/home/cristian/Tesis/Algorithm/Tessellation/voro.py", line 41, in voronoi_tessellation
    voro_features = hc_voronoi(feature, candidates, npoints, maxsize)
  File "/home/cristian/Tesis/Algorithm/Tessellation/voro.py", line 106, in hc_voronoi
    result_features = voronoi(feature, voro_points)
  File "/home/cristian/Tesis/Algorithm/Tessellation/voro.py", line 157, in voronoi
    final.append(geom.intersection(voro_poly))
  File "/usr/local/lib/python2.7/dist-packages/shapely/geometry/base.py", line 381, in intersection
    return geom_factory(self.impl['intersection'](self, other))
  File "/usr/local/lib/python2.7/dist-packages/shapely/topology.py", line 50, in __call__
    "The operation '%s' produced a null geometry. Likely cause is invalidity of the 'other' geometry %s" % (self.fn.__name__, repr(other)))
shapely.geos.TopologicalError: The operation 'GEOSIntersection_r' produced a null geometry. Likely cause is invalidity of  the 'other' geometry <shapely.geometry.polygon.Polygon object at 0x43e5a50>

***********************************************************************************************************************


Traceback (most recent call last):
  File "geo.py", line 279, in <module>
    size(geo_usos, courts, roads, 5 * 10000, context, "voro_sta_carla")
  File "geo.py", line 195, in size
    uso, npoints, courts_shape, roads_shape, max_size)
  File "/home/cristian/Tesis/Algorithm/Tessellation/voro.py", line 41, in voronoi_tessellation
    voro_features = hc_voronoi(feature, candidates, npoints, maxsize)
  File "/home/cristian/Tesis/Algorithm/Tessellation/voro.py", line 115, in hc_voronoi
    result_features = voronoi(feature, voro_points)
  File "/home/cristian/Tesis/Algorithm/Tessellation/voro.py", line 172, in voronoi
    final_union = cascaded_union(final)
  File "/usr/local/lib/python2.7/dist-packages/shapely/ops.py", line 110, in cascaded_union
    return geom_factory(lgeos.methods['cascaded_union'](collection))
  File "/usr/local/lib/python2.7/dist-packages/shapely/geometry/base.py", line 32, in geom_factory
    raise ValueError("No Shapely geometry can be created from null value")
ValueError: No Shapely geometry can be created from null value

